# TODO: Better to put linter's configuration to .golangci.yml
golangci-lint run --disable-all \
    -E revive \
    -E deadcode \
    -E errcheck \
    -E gosimple \
    -E govet \
    -E ineffassign \
    -E staticcheck \
    -E structcheck \
    -E typecheck \
    -E unused \
    -E varcheck \
    -E gocritic \
    -E lll \
    -E prealloc \
    -E gosec \
    -E gomnd \
    -E goconst \
    -E misspell \
    -E nakedret \
    -E unparam